version: "3"

services:
  server:
    ports:
      - '8080:8080'
    networks:
      - backend
    depends_on:
      - cache
    build:
      context: .
      dockerfile: Dockerfile

  cache:
    ports:
      - '6379:6379'
    networks:
      - backend
    image: 'redis:alpine'

networks:
  backend:
    driver: bridge