name: GolangTest
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest

      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: go mod .

      - name: Test
        run: go test./...

      - name: Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54